#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points
domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        get_subdomain_info "$sub"
    done
else
    get_subdomain_info "$subdomain"
fi
