#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me
# is redirecting to another page.
sudo apt-get update

sudo apt-get install -y nginx

echo 'server {
    listen 80;
    default_server;

    location /redirect_me {
        return 301 https://www.linkedin.com/in/mai-mohamed-rezk-010186177/;
    }

}'
