#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web1 54.173.91.144:80 check
        server web2 54.157.134.6:80 check" | sudo tee /etc/haproxy/haproxy.cfg

sudo systemctl enable haproxy
sudo systemctl restart haproxy
