#!/usr/bin/env bash
# container’s Nginx installation from listening on port 80
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.backup
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
