#!/usr/bin/env bash
# Configure Nginx to listen on port 80 for all active IPv4 IPs
sed -i 's/listen 8080;/listen 80;/g' /etc/nginx/sites-enabled/default
# Restart Nginx service
sudo service nginx restart
